"""
Email notification service for ClawBoard.

Sends PR-ready and dispatch status emails via Gmail SMTP.
Can also be used standalone from the command line for OpenClaw skills.

Usage (standalone):
    python services/email_service.py \
        --subject "PR Ready: fix-login-bug" \
        --body "PR #42 is ready for review" \
        --pr-url "https://github.com/user/repo/pull/42"

Env vars required:
    GOOGLE_APP_PASSWORD  — Gmail App Password (16-char)
    EMAIL_SENDER         — (optional) defaults to yeungsys1314@gmail.com
    EMAIL_RECIPIENTS     — (optional) comma-separated, defaults to yeungsys1314@gmail.com,ylchan7200@gmail.com
"""

import os
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional

logger = logging.getLogger(__name__)

# Defaults
DEFAULT_SENDER = "yeungsys1314@gmail.com"
DEFAULT_RECIPIENTS = ["yeungsys1314@gmail.com"]
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


class EmailService:
    """Gmail SMTP email sender for ClawBoard notifications."""

    def __init__(
        self,
        sender: Optional[str] = None,
        recipients: Optional[list[str]] = None,
        app_password: Optional[str] = None,
    ):
        self.sender = sender or os.getenv("EMAIL_SENDER", DEFAULT_SENDER)
        self.app_password = app_password or os.getenv("GOOGLE_APP_PASSWORD", "")

        recipients_env = os.getenv("EMAIL_RECIPIENTS", "")
        if recipients:
            self.recipients = recipients
        elif recipients_env:
            self.recipients = [r.strip() for r in recipients_env.split(",") if r.strip()]
        else:
            self.recipients = DEFAULT_RECIPIENTS

    def _build_pr_html(
        self,
        task_title: str,
        pr_url: str,
        project_name: str = "",
        dispatch_id: Optional[int] = None,
        output_summary: str = "",
    ) -> str:
        """Build an HTML email body for PR-ready notifications."""
        project_line = f"<p><strong>Project:</strong> {project_name}</p>" if project_name else ""
        dispatch_line = f"<p><strong>Dispatch:</strong> #{dispatch_id}</p>" if dispatch_id else ""
        output_block = ""
        if output_summary:
            output_block = f"""
            <div style="background: #f4f4f4; padding: 12px; border-radius: 6px; margin-top: 12px; font-family: monospace; font-size: 13px; white-space: pre-wrap;">
{output_summary}
            </div>"""

        return f"""
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: #1a73e8; color: white; padding: 20px; border-radius: 8px 8px 0 0;">
                <h2 style="margin: 0;">🎉 Pull Request Ready for Review</h2>
            </div>
            <div style="padding: 20px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 8px 8px;">
                <p><strong>Task:</strong> {task_title}</p>
                {project_line}
                {dispatch_line}
                <p style="margin-top: 16px;">
                    <a href="{pr_url}"
                       style="display: inline-block; background: #1a73e8; color: white; padding: 12px 24px;
                              border-radius: 6px; text-decoration: none; font-weight: bold;">
                        🔗 View Pull Request on GitHub
                    </a>
                </p>
                {output_block}
                <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;">
                <p style="color: #666; font-size: 12px;">
                    Sent automatically by ClawBoard • Generated by Claude Code via OpenClaw
                </p>
            </div>
        </div>
        """

    def _build_completed_html(
        self,
        task_title: str,
        project_name: str = "",
        dispatch_id: Optional[int] = None,
        output_summary: str = "",
    ) -> str:
        """Build an HTML email body for task-completed notifications (no PR)."""
        project_line = f"<p><strong>Project:</strong> {project_name}</p>" if project_name else ""
        dispatch_line = f"<p><strong>Dispatch:</strong> #{dispatch_id}</p>" if dispatch_id else ""
        output_block = ""
        if output_summary:
            output_block = f"""
            <div style="background: #f4f4f4; padding: 12px; border-radius: 6px; margin-top: 12px; font-family: monospace; font-size: 13px; white-space: pre-wrap;">
{output_summary}
            </div>"""

        return f"""
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: #2e7d32; color: white; padding: 20px; border-radius: 8px 8px 0 0;">
                <h2 style="margin: 0;">✅ Task Completed</h2>
            </div>
            <div style="padding: 20px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 8px 8px;">
                <p><strong>Task:</strong> {task_title}</p>
                {project_line}
                {dispatch_line}
                <p style="margin-top: 12px; color: #555;">Task completed successfully. No pull request was created for this dispatch.</p>
                {output_block}
                <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;">
                <p style="color: #666; font-size: 12px;">
                    Sent automatically by ClawBoard • Generated by Claude Code via OpenClaw
                </p>
            </div>
        </div>
        """

    def _build_status_html(
        self,
        task_title: str,
        status: str,
        dispatch_id: Optional[int] = None,
        error_reason: str = "",
        output_summary: str = "",
    ) -> str:
        """Build an HTML email body for dispatch status notifications (failed/stopped)."""
        emoji = "❌" if status == "failed" else "⏸️"
        color = "#d32f2f" if status == "failed" else "#f57c00"
        status_label = status.upper()

        error_block = ""
        if error_reason:
            error_block = f"<p><strong>Reason:</strong> {error_reason}</p>"

        output_block = ""
        if output_summary:
            output_block = f"""
            <div style="background: #f4f4f4; padding: 12px; border-radius: 6px; margin-top: 12px; font-family: monospace; font-size: 13px; white-space: pre-wrap;">
{output_summary}
            </div>"""

        return f"""
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: {color}; color: white; padding: 20px; border-radius: 8px 8px 0 0;">
                <h2 style="margin: 0;">{emoji} Dispatch {status_label}</h2>
            </div>
            <div style="padding: 20px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 8px 8px;">
                <p><strong>Task:</strong> {task_title}</p>
                <p><strong>Dispatch:</strong> #{dispatch_id}</p>
                {error_block}
                {output_block}
                <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;">
                <p style="color: #666; font-size: 12px;">
                    Sent automatically by ClawBoard • Generated by Claude Code via OpenClaw
                </p>
            </div>
        </div>
        """

    def send(
        self,
        subject: str,
        html_body: str,
        recipients: Optional[list[str]] = None,
    ) -> bool:
        """Send an email via Gmail SMTP.

        Returns True on success, False on failure (logs the error).
        """
        if not self.app_password:
            logger.error("GOOGLE_APP_PASSWORD not set — cannot send email")
            return False

        to_list = recipients or self.recipients
        if not to_list:
            logger.error("No recipients specified — cannot send email")
            return False

        msg = MIMEMultipart("alternative")
        msg["From"] = self.sender
        msg["To"] = ", ".join(to_list)
        msg["Subject"] = subject
        msg.attach(MIMEText(html_body, "html"))

        try:
            with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                server.starttls()
                server.login(self.sender, self.app_password)
                server.sendmail(self.sender, to_list, msg.as_string())
            logger.info(f"Email sent to {to_list}: {subject}")
            return True
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False

    def send_pr_notification(
        self,
        task_title: str,
        pr_url: str,
        project_name: str = "",
        dispatch_id: Optional[int] = None,
        output_summary: str = "",
    ) -> bool:
        """Send a PR-ready notification email."""
        subject = f"🎉 PR Ready: {task_title}"
        html = self._build_pr_html(
            task_title=task_title,
            pr_url=pr_url,
            project_name=project_name,
            dispatch_id=dispatch_id,
            output_summary=output_summary,
        )
        return self.send(subject, html)

    def send_dispatch_status(
        self,
        task_title: str,
        status: str,
        dispatch_id: Optional[int] = None,
        error_reason: str = "",
        output_summary: str = "",
    ) -> bool:
        """Send a dispatch failed/stopped notification email."""
        emoji = "❌" if status == "failed" else "⏸️"
        subject = f"{emoji} Dispatch {status}: {task_title}"
        html = self._build_status_html(
            task_title=task_title,
            status=status,
            dispatch_id=dispatch_id,
            error_reason=error_reason,
            output_summary=output_summary,
        )
        return self.send(subject, html)


# ── Standalone CLI ──────────────────────────────────────────────

def main():
    """CLI entry point for sending emails from shell scripts / OpenClaw skills."""
    import argparse

    parser = argparse.ArgumentParser(description="Send email notification via Gmail SMTP")
    parser.add_argument("--subject", required=True, help="Email subject line")
    parser.add_argument("--body", default="", help="Plain text body (used if --html not given)")
    parser.add_argument("--html", default="", help="HTML body content")
    parser.add_argument("--pr-url", default="", help="GitHub PR URL (generates PR template)")
    parser.add_argument("--task-title", default="", help="Task title for PR template")
    parser.add_argument("--project-name", default="", help="Project name for PR template")
    parser.add_argument("--recipients", default="", help="Comma-separated recipient emails")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    recipients = [r.strip() for r in args.recipients.split(",") if r.strip()] if args.recipients else None
    svc = EmailService(recipients=recipients)

    if args.pr_url:
        # PR notification mode
        ok = svc.send_pr_notification(
            task_title=args.task_title or args.subject,
            pr_url=args.pr_url,
            project_name=args.project_name,
        )
    else:
        # Generic email mode
        html = args.html or f"<p>{args.body}</p>"
        ok = svc.send(subject=args.subject, html_body=html, recipients=recipients)

    exit(0 if ok else 1)


if __name__ == "__main__":
    main()
